<a href="https://colab.research.google.com/github/5rangeclick/DL/blob/main/Pytorch_0818.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import torch
import numpy as np
import torch #파이토치 딥러닝 프레임워크
import torch.nn as nn #선형식을 선언하기 위해 씀
import torch.nn.functional as F #수학적 함수를 불러올 때
import torch.optim as optim # 옵티마이저 불러오려고


In [ ]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t) #FloatTensor로 감싸주면 타입이 바뀜. ft라는 3차원의 데이터로.

In [ ]:
print(ft.shape) #길이가 3인 ~~ 배열이 2개.. 3차원 배열

torch.Size([2, 2, 3])


In [ ]:
ft.view(-1,2) #view: 차원을 변형해주는 함수. 파이썬 내장함수가 아닌 torch.FloatTensor의 내장함수임.

tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]])

In [ ]:
(3,1,-1)#열의 사이즈가 3, 데이터가 하나, 나머지는 너 알아서 해라(=-1)

In [ ]:
narray = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

tf_array = torch.FloatTensor(narray)
print(ft_array)

tf_array.view(-1)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:

#스퀴즈 = 줄인다
#3,1의
ft = torch.FloatTensor()

In [ ]:
#언스퀴즈. 차원이 추가된다.
un_ft = ft.unsqueeze(0)#인덱스로 생각하기 = 0번째 인덱스를 추가해라 =첫번째 인덱스
ft.unsqueeze(-1) #마지막을 추가해라
print(un_ft)
print

In [30]:
import torch #파이토치 딥러닝 프레임워크
import torch.nn as nn #선형식을 선언하기 위해 씀
import torch.nn.functional as F #수학적 함수를 불러올 때
import torch.optim as optim # 옵티마이저 불러오려고


In [ ]:
# 현재 실습하고 있는 파이썬 코드를 재실행해도 다음에도 같은 결과가 나오도록 랜덤 시드(random seed)를 줍니다.
# torch.manual_seed(1)


In [ ]:
#허리둘레로 몸무게 예측
x_train = torch.FloatTensor([[32], [29], [26]]) #cm
y_train = torch.FloatTensor([[77], [70], [65]]) #kg

In [ ]:
print(x_train)
print(x_train.shape) #3개의 데이터, 하나의 피쳐값

tensor([[32.],
        [29.],
        [26.]])
torch.Size([3, 1])


In [ ]:
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [ ]:
print(W)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [ ]:
#예측값과 정답값의 차이를 계산하기 위해 loss가 필요, ~하기 위해 옵티마이저 설정

In [ ]:
# optimizer 설정
optimizer = optim.Adam([W, b], lr=0.01) #아담의 특성: 모멘텀과 스텝사이즈 두 가지를 고려해서 만듦. 너는 모델에서 W랑 b만 업데이트 시켜.
#learnable parameter
#보폭 사이즈

In [ ]:
epochs = 1999 # 원하는만큼 경사 하강법을 반복 #전체데이터를 몇 번 훑을 거야?

In [ ]:
for epoch in range(epochs):

    #모델 식
    predict = W * x_train + b # y = WX + b 선형회귀를 위한 일차방정식

    # cost 계산
    cost = torch.mean((predict - y_train) ** 2) #MSE. 민스퀘어에러

    #RMSE(루트민스퀘어에러) 계산 = cost ** (1/2)



    # cost로 모델 식 개선
    optimizer.zero_grad() #기울기를 스텝마다 다시 구해야 하므로, 옵티가 가지고 있는 기울기를 초기화. for문 시작에 넣을 수도 있음.
    cost.backward() #역전파하는 게 아니라, 코스트에 대한 기울기를 구하는 것.
    optimizer.step() #이때 역전파

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 2.316, b: 3.449 Cost: 0.824220
Epoch  100/1999 W: 2.314, b: 3.506 Cost: 0.816759
Epoch  200/1999 W: 2.312, b: 3.566 Cost: 0.809016
Epoch  300/1999 W: 2.310, b: 3.628 Cost: 0.800980
Epoch  400/1999 W: 2.307, b: 3.694 Cost: 0.792655
Epoch  500/1999 W: 2.305, b: 3.762 Cost: 0.784026
Epoch  600/1999 W: 2.303, b: 3.833 Cost: 0.775100
Epoch  700/1999 W: 2.300, b: 3.907 Cost: 0.765870
Epoch  800/1999 W: 2.297, b: 3.984 Cost: 0.756338
Epoch  900/1999 W: 2.295, b: 4.065 Cost: 0.746497
Epoch 1000/1999 W: 2.292, b: 4.148 Cost: 0.736349
Epoch 1100/1999 W: 2.289, b: 4.235 Cost: 0.725893
Epoch 1200/1999 W: 2.286, b: 4.326 Cost: 0.715133
Epoch 1300/1999 W: 2.282, b: 4.420 Cost: 0.704072
Epoch 1400/1999 W: 2.279, b: 4.518 Cost: 0.692719
Epoch 1500/1999 W: 2.276, b: 4.619 Cost: 0.681075
Epoch 1600/1999 W: 2.272, b: 4.725 Cost: 0.669154
Epoch 1700/1999 W: 2.268, b: 4.834 Cost: 0.656955
Epoch 1800/1999 W: 2.264, b: 4.947 Cost: 0.644492
Epoch 1900/1999 W: 2.260, b: 5.064 Cost: 0.631789


# 다중 선형 회귀

In [ ]:
# 다중 선형 회귀 = x가 여러 개인 거

In [ ]:
x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  80],
                               [96,  98,  100],
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])


In [ ]:
# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [ ]:
print(W)
print(b)

tensor([[0.],
        [0.],
        [0.]], requires_grad=True)
tensor([0.], requires_grad=True)


In [11]:
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5) #확률적경사하강법, 업데이트대상 W,b, 학습률(보폭) 0.00001

In [12]:
epochs = 20
for epoch in range(epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b #matmul 매트릭스 멀티플. 다중? 행렬곱 해주는 문법

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7861,  95.8280]) Cost: 3069.590820
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670288
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.481964
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9731, 169.8976, 192.0301, 136.5279]) Cost: 38.687401
Epoch    7/20 hypothesis: tensor([151.1574, 181.6347, 172.4254, 194.8856, 138.5585]) Cost: 16.499046
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5042, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4216, 140.3625]) Cost: 7.071105
Epoch   10/20 hyp

# nn.Module로 구현하는 선형 회귀

In [31]:
# import torch.nn as nn
# model = nn.Linear(input_dim, output_dim) #넣어주면 하나의 선형식을 만들 수 있다.

In [57]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [58]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
model = nn.Linear(3,1) # y = W1x1 + W2x2 + W3x3

In [59]:
print(list(model.parameters())) #모델이 가진 파라미터 출력 => W 3개랑 b 1개, W랑 b는 처음에는 랜덤으로 설정된다. 유지하려면 랜덤 시드 박아주

[Parameter containing:
tensor([[-0.4429, -0.3880,  0.1532]], requires_grad=True), Parameter containing:
tensor([0.1823], requires_grad=True)]


In [60]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) #모델이 가지고 있는 파라미터들을 업데이트할 준비를 해줘

In [61]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train) #모델에 괄호치고 데이터를 넣음

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수 #수학적 함수가 들어간 F라는 모듈. 거기에 mse loss함수가 들어있음.

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 52758.070312
Epoch  100/2000 Cost: 1.809262
Epoch  200/2000 Cost: 1.760202
Epoch  300/2000 Cost: 1.713581
Epoch  400/2000 Cost: 1.669219
Epoch  500/2000 Cost: 1.627039
Epoch  600/2000 Cost: 1.586871
Epoch  700/2000 Cost: 1.548641
Epoch  800/2000 Cost: 1.512261
Epoch  900/2000 Cost: 1.477626
Epoch 1000/2000 Cost: 1.444638
Epoch 1100/2000 Cost: 1.413204
Epoch 1200/2000 Cost: 1.383258
Epoch 1300/2000 Cost: 1.354706
Epoch 1400/2000 Cost: 1.327503
Epoch 1500/2000 Cost: 1.301570
Epoch 1600/2000 Cost: 1.276813
Epoch 1700/2000 Cost: 1.253191
Epoch 1800/2000 Cost: 1.230658
Epoch 1900/2000 Cost: 1.209140
Epoch 2000/2000 Cost: 1.188563


# 클래스로 파이토치 모델 구현하기

In [37]:
class LinearRegressionModel(nn.Module): # torch.nn.Module을 상속받는 파이썬 클래스
    def __init__(self): #
        super().__init__() #nn.모듈 한테 상속을 받음. 부모클래스의 init함수를 가져옴
        self.linear = nn.Linear(1, 1) #모델의 아키텍쳐? 초기화 # 단순 선형 회귀이므로 input_dim=1, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [39]:
#model = nn.Linear(1,1) 이걸 클래스 형태로 만든 거임
model = LinearRegressionModel() #모델 불러옴

# appendix

In [43]:
class Sonata: #소나타 설계도
    def __init__(self, color):
        self.price = 2000
        self.km =15
        self.color = color
    def drive(self): #드라이브함수를 가지고 태어남
        print("주행을 시작합니다")


yhw_Sonata = Sonata("black") #내 소나타. 초기함수에서 블랙 값이 color이 들어감. self는 객체. self=yhw_Sonata가 되는 것.
ldb_Sonata = Sonata("red")

In [44]:
print(yhw_Sonata.color)

black


In [46]:
yhw_Sonata.drive()

주행을 시작합니다


In [ ]:
class Car:
    def __init__(self):
        self.price = 3000
        self.color = color
        self.km =15

class electric_Avante(Car):
    def __init__(self, color): #부모 클래스에서 가지고 있는 모든 변수를 가져와서 초기화시켜라
        super().__init__(color)
        self.battery = 10000

yhw_elect_Avante = electric_Avante("black")

print("부모클래스에서 물려받은 멤버변수 km 확인", yhw_elect_Avante.km)
print("부모클래스에서 물려받은 멤버변수 color 확인", yhw_elect_Avante.color)
print("부모클래스에서 물려받은 멤버변수 price 확인", yhw_elect_Avante.price)
print("자기 자신이 원래 가지고 있던 멤버변수 battery 확인", yhw_elect_Avante.battery)

In [ ]:
#부모클래스 : 휴먼 멤버변수는 에이지는 10, 젠더는 여자
자식클ㄹ래스: 스튜던트 멤버변수는 스튜던트_no

다음 결과가 나오도록
yhw_student = Student(100) #학생번호 100
print("학생번호", yhw_student.student)

In [12]:
class Human:
    def __init__(self):
        self.age = 10
        self.gender = "여자"

class Student(Human):
    def __init__(self, student_no):
        super().__init__()
        self.student_no =student_no


In [13]:
yhw_student = Student(100) #학생번호 100
print("학생번호", yhw_student.student_no)
print("학생나이", yhw_student.age)

학생번호 100
학생나이 10


# 이중 상속

In [21]:
class Human: #할머니
    def __init__(self):
        self.age = 10
        self.gender = "여자"
    def asdf(self):
        print("하하")

class Student(Human): #아빠
    def __init__(self, student_no):
        super().__init__()
        self.student_no =student_no
    def qwer(self):
        print("배부르다")

class Test(Student): #Test는 자기가 가지고 있는 변수는 없다
    def __init__(self, student_no):
        super().__init__(student_no)

yhw_student = Student(100) #학생번호 100
print("학생번호", yhw_student.student_no)
print("학생나이", yhw_student.age)


학생번호 100
학생나이 10


In [22]:
yhw_student.qwer()  #아빠거

배부르다


In [23]:
yhw_student.asdf() #할머니거

하하


In [27]:
class Human: #할머니
    def __init__(self):
        self.age = 10
        self.gender = "여자"
    def asdf(self):
        print("하하")

class Student(Human): #아빠
    def __init__(self, student_no):
        super().__init__()
        self.student_no =student_no
    def qwer(self):
        print("배부르다")

class Test(Student): #Test는 자기가 가지고 있는 변수는 없다
    def __init__(self, student_no):
        Student.__init__(student_no)
        Human.__init__(student_no)

yhw_student = Student(100) #학생번호 100
print("학생번호", yhw_student.student_no)
print("학생나이", yhw_student.age)


학생번호 100
학생나이 10


# 클래스로 파이토치 모델 구현하기

In [36]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [42]:
class LinearRegressionModel(nn.Module): # torch.nn.Module을 상속받는 파이썬 클래스
    def __init__(self): #
        super().__init__() #nn.모듈 한테 상속을 받음. 부모클래스의 init함수를 가져옴
        self.linear = nn.Linear(3, 1) #모델의 아키텍쳐? 초기화 # 단순 선형 회귀이므로 input_dim=1, output_dim=1.

    def forward(self, x): #이 x 자리에 밑에서 x_train이 들어옴.
        return self.linear(x)

In [43]:
#model = nn.Linear(1,1) 이걸 클래스 형태로 만든 거임
model = LinearRegressionModel() #모델 불러옴

In [44]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [45]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):
    # H(x) 계산
    prediction = model(x_train) #포워드로 들어가서 그게
    # model(x_train)은 model.forward(x_train)와 동일함.
    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수
    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()
    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 33392.781250
Epoch  100/2000 Cost: 14.843318
Epoch  200/2000 Cost: 14.080205
Epoch  300/2000 Cost: 13.357303
Epoch  400/2000 Cost: 12.672513
Epoch  500/2000 Cost: 12.023758
Epoch  600/2000 Cost: 11.409191
Epoch  700/2000 Cost: 10.826982
Epoch  800/2000 Cost: 10.275474
Epoch  900/2000 Cost: 9.752952
Epoch 1000/2000 Cost: 9.257975
Epoch 1100/2000 Cost: 8.789070
Epoch 1200/2000 Cost: 8.344844
Epoch 1300/2000 Cost: 7.923991
Epoch 1400/2000 Cost: 7.525289
Epoch 1500/2000 Cost: 7.147565
Epoch 1600/2000 Cost: 6.789725
Epoch 1700/2000 Cost: 6.450704
Epoch 1800/2000 Cost: 6.129553
Epoch 1900/2000 Cost: 5.825295
Epoch 2000/2000 Cost: 5.537011


# 03-06 미니 배치와 데이터 로드(Mini Batch and Data Load)

# 03-07 커스텀 데이터셋(Custom Dataset)




In [ ]:
#데이터 전처리, 미니배치 등을 클래스화한 걸 커스텀 데이터셋이라고 한다.